### ISSUE TITLE
Base64 string encoder plugin

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#750]
**Is your feature request related to a problem? Please describe.**
Plugin that encodes base64 string. This plugin is very simple in terms of python. The challenge is to add it as plugin to Tracardi. This is also very simple if you read this http://docs.tracardi.com/plugins/tutorial/part1/ and http://docs.tracardi.com/plugins/tutorial/part2

**Describe the solution you'd like**
User defines in plugin configuration what strings should be encoded. 

Example of configuration 

```json
{
   "value": "event@properties.some_value1"
}
```

Input:
Workflow payload

Output:
Encoded string

**Additional context**
You will need to setup the dev environment. Here is the tutorial how to do it. Also to understand how the plugins work please read http://docs.tracardi.com/plugins/tutorial/part1/ and http://docs.tracardi.com/plugins/tutorial/part2/ . The next part is o its way so you can extend your knowledge about Tracardi plugins.

**Comment by knittl** [comment]
I should be able to implement this feature and #749. I'll start working on it, can you assign me both tickets?

**Comment by knittl** [comment]
I have the first draft of both plugins, but I'm unable to get the plugin to show up in the tracardi-gui. I followed the steps at <http://docs.tracardi.com/plugins/tutorial/part1/>, but somehow the new plugin doesn't end up being visible for the API/UI. I see that the API depends on the Git version of the library, so it is clear that it will not see local development. Is there a switch to enable so that the local files will be used as dependency?

**Comment by knittl** [comment]
Nevermind. I have figured it out; added to the wrong list :-/ Still need to refresh dependencies and restart API, but this is mentioned in the tutorial.

**Comment by knittl** [comment]
I see that the documentation for the plugins/actions is done in the API project. How should I link the PRs in the API and the library project? Or should I first wait for #750 and #749 to be merged?

**Comment by atompie** [comment]
@knittl please link it to the PR.
