### ISSUE TITLE
Plugin that integrates with google sheets

### ISSUE THREAD

**Issue by atompie** [Tracardi/tracardi#88]
# Documentation

https://developers.google.com/sheets/api/quickstart/python

**Comment by emge1** [comment]
.

**Comment by atompie** [comment]
@emge1 What is the status of this task

**Comment by emge1** [comment]
@atompie Hi, I think the plugin is done. Here is the repository: https://github.com/emge1/tracardi-airtable-integrator. The manual test was passed.
I am only thinking about adding some pictures to README.md to make it easier to learn. And I'll probably change the examples in convention of Tracardi docs

**Comment by emge1** [comment]
@atompie I didn't finished this task. Here is my repo: https://github.com/emge1/tracardi-google-sheets-integrator
I downloaded credentials from Google Cloud Console, but the error was raised ('ValueError: Service account info was not in the expected format, missing fields token_uri, client_email.')
Probably I could write it manually but IMO it could be very discouraged for customer if he need to copy and paste the data as email and so on
WhenI downloaded credentials on another way, antoher error was raised (403 on the terminal 'Details: "Requested entity was not found.' and 404 in the link returned in the terminal 'the request is missing a valid API key')
That's why the core of the plugin is correct IMO. If the plugin works, it should be able to read and write range or ranges in google sheets.
I think there is a solution of the problem and there is a way to make it working and comfortable, I'll try to solve it

**Comment by emge1** [comment]
@atompie I think it's done. The plugin passed manual tests
Here is my repo: https://github.com/emge1/tracardi-google-sheets-integrator

**Comment by fabform** [comment]
Handy to get the google sheets id
[how to get google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by atompie** [comment]
@emge1 This plugin was integrated with Tracardi now
